export enum CONDITION_TYPE {
  READY = "Ready",
  HEALTHY = "Healthy",
  RELEASED = "Released",
  AVAILABLE = "Available",
  PROGRESSING = "Progressing",
  RECONCILING = "Reconciling",
  FAILED = "Failed",
  UNHEALTHY = "Unhealthy",
}

export const SUCCESS_TYPES = [CONDITION_TYPE.READY, CONDITION_TYPE.HEALTHY, CONDITION_TYPE.RELEASED, CONDITION_TYPE.AVAILABLE];
export const INFO_TYPES = [CONDITION_TYPE.PROGRESSING, CONDITION_TYPE.RECONCILING];
export const ERROR_TYPES = [CONDITION_TYPE.FAILED, CONDITION_TYPE.UNHEALTHY];
