// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	metrics "github.com/timp4w/phi/internal/core/metrics"
)

// MetricsService is an autogenerated mock type for the MetricsService type
type MetricsService struct {
	mock.Mock
}

type MetricsService_Expecter struct {
	mock *mock.Mock
}

func (_m *MetricsService) EXPECT() *MetricsService_Expecter {
	return &MetricsService_Expecter{mock: &_m.Mock}
}

// GetResourceMetrics provides a mock function with given fields: ctx, uid, rng
func (_m *MetricsService) GetResourceMetrics(ctx context.Context, uid string, rng string) (metrics.ResourceMetrics, error) {
	ret := _m.Called(ctx, uid, rng)

	if len(ret) == 0 {
		panic("no return value specified for GetResourceMetrics")
	}

	var r0 metrics.ResourceMetrics
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (metrics.ResourceMetrics, error)); ok {
		return rf(ctx, uid, rng)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) metrics.ResourceMetrics); ok {
		r0 = rf(ctx, uid, rng)
	} else {
		r0 = ret.Get(0).(metrics.ResourceMetrics)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, uid, rng)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MetricsService_GetResourceMetrics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetResourceMetrics'
type MetricsService_GetResourceMetrics_Call struct {
	*mock.Call
}

// GetResourceMetrics is a helper method to define mock.On call
//   - ctx context.Context
//   - uid string
//   - rng string
func (_e *MetricsService_Expecter) GetResourceMetrics(ctx interface{}, uid interface{}, rng interface{}) *MetricsService_GetResourceMetrics_Call {
	return &MetricsService_GetResourceMetrics_Call{Call: _e.mock.On("GetResourceMetrics", ctx, uid, rng)}
}

func (_c *MetricsService_GetResourceMetrics_Call) Run(run func(ctx context.Context, uid string, rng string)) *MetricsService_GetResourceMetrics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MetricsService_GetResourceMetrics_Call) Return(_a0 metrics.ResourceMetrics, _a1 error) *MetricsService_GetResourceMetrics_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MetricsService_GetResourceMetrics_Call) RunAndReturn(run func(context.Context, string, string) (metrics.ResourceMetrics, error)) *MetricsService_GetResourceMetrics_Call {
	_c.Call.Return(run)
	return _c
}

// GetCurrentUsage provides a mock function with given fields: ctx, uids
func (_m *MetricsService) GetCurrentUsage(ctx context.Context, uids []string) (map[string]metrics.CurrentUsage, error) {
	ret := _m.Called(ctx, uids)

	if len(ret) == 0 {
		panic("no return value specified for GetCurrentUsage")
	}

	var r0 map[string]metrics.CurrentUsage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) (map[string]metrics.CurrentUsage, error)); ok {
		return rf(ctx, uids)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string) map[string]metrics.CurrentUsage); ok {
		r0 = rf(ctx, uids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]metrics.CurrentUsage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(ctx, uids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MetricsService_GetCurrentUsage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCurrentUsage'
type MetricsService_GetCurrentUsage_Call struct {
	*mock.Call
}

// GetCurrentUsage is a helper method to define mock.On call
//   - ctx context.Context
//   - uids []string
func (_e *MetricsService_Expecter) GetCurrentUsage(ctx interface{}, uids interface{}) *MetricsService_GetCurrentUsage_Call {
	return &MetricsService_GetCurrentUsage_Call{Call: _e.mock.On("GetCurrentUsage", ctx, uids)}
}

func (_c *MetricsService_GetCurrentUsage_Call) Run(run func(ctx context.Context, uids []string)) *MetricsService_GetCurrentUsage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string))
	})
	return _c
}

func (_c *MetricsService_GetCurrentUsage_Call) Return(_a0 map[string]metrics.CurrentUsage, _a1 error) *MetricsService_GetCurrentUsage_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MetricsService_GetCurrentUsage_Call) RunAndReturn(run func(context.Context, []string) (map[string]metrics.CurrentUsage, error)) *MetricsService_GetCurrentUsage_Call {
	_c.Call.Return(run)
	return _c
}

// GetStorageUsage provides a mock function with given fields: ctx, uids
func (_m *MetricsService) GetStorageUsage(ctx context.Context, uids []string) (map[string]metrics.StorageUsage, error) {
	ret := _m.Called(ctx, uids)

	if len(ret) == 0 {
		panic("no return value specified for GetStorageUsage")
	}

	var r0 map[string]metrics.StorageUsage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) (map[string]metrics.StorageUsage, error)); ok {
		return rf(ctx, uids)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string) map[string]metrics.StorageUsage); ok {
		r0 = rf(ctx, uids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]metrics.StorageUsage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(ctx, uids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MetricsService_GetStorageUsage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStorageUsage'
type MetricsService_GetStorageUsage_Call struct {
	*mock.Call
}

// GetStorageUsage is a helper method to define mock.On call
//   - ctx context.Context
//   - uids []string
func (_e *MetricsService_Expecter) GetStorageUsage(ctx interface{}, uids interface{}) *MetricsService_GetStorageUsage_Call {
	return &MetricsService_GetStorageUsage_Call{Call: _e.mock.On("GetStorageUsage", ctx, uids)}
}

func (_c *MetricsService_GetStorageUsage_Call) Run(run func(ctx context.Context, uids []string)) *MetricsService_GetStorageUsage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string))
	})
	return _c
}

func (_c *MetricsService_GetStorageUsage_Call) Return(_a0 map[string]metrics.StorageUsage, _a1 error) *MetricsService_GetStorageUsage_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MetricsService_GetStorageUsage_Call) RunAndReturn(run func(context.Context, []string) (map[string]metrics.StorageUsage, error)) *MetricsService_GetStorageUsage_Call {
	_c.Call.Return(run)
	return _c
}

// GetNodeUsage provides a mock function with given fields: ctx
func (_m *MetricsService) GetNodeUsage(ctx context.Context) ([]metrics.NodeUsage, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetNodeUsage")
	}

	var r0 []metrics.NodeUsage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]metrics.NodeUsage, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []metrics.NodeUsage); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]metrics.NodeUsage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MetricsService_GetNodeUsage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNodeUsage'
type MetricsService_GetNodeUsage_Call struct {
	*mock.Call
}

// GetNodeUsage is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MetricsService_Expecter) GetNodeUsage(ctx interface{}) *MetricsService_GetNodeUsage_Call {
	return &MetricsService_GetNodeUsage_Call{Call: _e.mock.On("GetNodeUsage", ctx)}
}

func (_c *MetricsService_GetNodeUsage_Call) Run(run func(ctx context.Context)) *MetricsService_GetNodeUsage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MetricsService_GetNodeUsage_Call) Return(_a0 []metrics.NodeUsage, _a1 error) *MetricsService_GetNodeUsage_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MetricsService_GetNodeUsage_Call) RunAndReturn(run func(context.Context) ([]metrics.NodeUsage, error)) *MetricsService_GetNodeUsage_Call {
	_c.Call.Return(run)
	return _c
}

// Status provides a mock function with no fields
func (_m *MetricsService) Status() metrics.IntegrationStatus {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Status")
	}

	var r0 metrics.IntegrationStatus
	if rf, ok := ret.Get(0).(func() metrics.IntegrationStatus); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(metrics.IntegrationStatus)
	}

	return r0
}

// MetricsService_Status_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Status'
type MetricsService_Status_Call struct {
	*mock.Call
}

// Status is a helper method to define mock.On call
func (_e *MetricsService_Expecter) Status() *MetricsService_Status_Call {
	return &MetricsService_Status_Call{Call: _e.mock.On("Status")}
}

func (_c *MetricsService_Status_Call) Run(run func()) *MetricsService_Status_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MetricsService_Status_Call) Return(_a0 metrics.IntegrationStatus) *MetricsService_Status_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MetricsService_Status_Call) RunAndReturn(run func() metrics.IntegrationStatus) *MetricsService_Status_Call {
	_c.Call.Return(run)
	return _c
}

// NewMetricsService creates a new instance of MetricsService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMetricsService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MetricsService {
	mock := &MetricsService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
