// Code generated by mockery v2.53.3. DO NOT EDIT.
//
// Kept in-package (not internal/testing/testdata) on purpose: a testdata mock
// of PrometheusService would import this package, creating an import cycle
// with this package's own internal tests. Not regenerated by make backend-mocks.

package prometheus

import (
	context "context"
	time "time"

	mock "github.com/stretchr/testify/mock"
	metrics "github.com/timp4w/phi/internal/core/metrics"
)

// MockPrometheusService is an autogenerated mock type for the PrometheusService type
type MockPrometheusService struct {
	mock.Mock
}

type MockPrometheusService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPrometheusService) EXPECT() *MockPrometheusService_Expecter {
	return &MockPrometheusService_Expecter{mock: &_m.Mock}
}

// Query provides a mock function with given fields: ctx, query, ts
func (_m *MockPrometheusService) Query(ctx context.Context, query string, ts time.Time) ([]SeriesResult, error) {
	ret := _m.Called(ctx, query, ts)

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 []SeriesResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) ([]SeriesResult, error)); ok {
		return rf(ctx, query, ts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) []SeriesResult); ok {
		r0 = rf(ctx, query, ts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]SeriesResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Time) error); ok {
		r1 = rf(ctx, query, ts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPrometheusService_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type MockPrometheusService_Query_Call struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - ts time.Time
func (_e *MockPrometheusService_Expecter) Query(ctx interface{}, query interface{}, ts interface{}) *MockPrometheusService_Query_Call {
	return &MockPrometheusService_Query_Call{Call: _e.mock.On("Query", ctx, query, ts)}
}

func (_c *MockPrometheusService_Query_Call) Run(run func(ctx context.Context, query string, ts time.Time)) *MockPrometheusService_Query_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(time.Time))
	})
	return _c
}

func (_c *MockPrometheusService_Query_Call) Return(_a0 []SeriesResult, _a1 error) *MockPrometheusService_Query_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPrometheusService_Query_Call) RunAndReturn(run func(context.Context, string, time.Time) ([]SeriesResult, error)) *MockPrometheusService_Query_Call {
	_c.Call.Return(run)
	return _c
}

// QueryRange provides a mock function with given fields: ctx, query, start, end, step
func (_m *MockPrometheusService) QueryRange(ctx context.Context, query string, start time.Time, end time.Time, step time.Duration) ([]SeriesResult, error) {
	ret := _m.Called(ctx, query, start, end, step)

	if len(ret) == 0 {
		panic("no return value specified for QueryRange")
	}

	var r0 []SeriesResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time, time.Duration) ([]SeriesResult, error)); ok {
		return rf(ctx, query, start, end, step)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time, time.Duration) []SeriesResult); ok {
		r0 = rf(ctx, query, start, end, step)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]SeriesResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Time, time.Time, time.Duration) error); ok {
		r1 = rf(ctx, query, start, end, step)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPrometheusService_QueryRange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryRange'
type MockPrometheusService_QueryRange_Call struct {
	*mock.Call
}

// QueryRange is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - start time.Time
//   - end time.Time
//   - step time.Duration
func (_e *MockPrometheusService_Expecter) QueryRange(ctx interface{}, query interface{}, start interface{}, end interface{}, step interface{}) *MockPrometheusService_QueryRange_Call {
	return &MockPrometheusService_QueryRange_Call{Call: _e.mock.On("QueryRange", ctx, query, start, end, step)}
}

func (_c *MockPrometheusService_QueryRange_Call) Run(run func(ctx context.Context, query string, start time.Time, end time.Time, step time.Duration)) *MockPrometheusService_QueryRange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(time.Time), args[3].(time.Time), args[4].(time.Duration))
	})
	return _c
}

func (_c *MockPrometheusService_QueryRange_Call) Return(_a0 []SeriesResult, _a1 error) *MockPrometheusService_QueryRange_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPrometheusService_QueryRange_Call) RunAndReturn(run func(context.Context, string, time.Time, time.Time, time.Duration) ([]SeriesResult, error)) *MockPrometheusService_QueryRange_Call {
	_c.Call.Return(run)
	return _c
}

// Status provides a mock function with no fields
func (_m *MockPrometheusService) Status() metrics.IntegrationStatus {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Status")
	}

	var r0 metrics.IntegrationStatus
	if rf, ok := ret.Get(0).(func() metrics.IntegrationStatus); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(metrics.IntegrationStatus)
	}

	return r0
}

// MockPrometheusService_Status_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Status'
type MockPrometheusService_Status_Call struct {
	*mock.Call
}

// Status is a helper method to define mock.On call
func (_e *MockPrometheusService_Expecter) Status() *MockPrometheusService_Status_Call {
	return &MockPrometheusService_Status_Call{Call: _e.mock.On("Status")}
}

func (_c *MockPrometheusService_Status_Call) Run(run func()) *MockPrometheusService_Status_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPrometheusService_Status_Call) Return(_a0 metrics.IntegrationStatus) *MockPrometheusService_Status_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPrometheusService_Status_Call) RunAndReturn(run func() metrics.IntegrationStatus) *MockPrometheusService_Status_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPrometheusService creates a new instance of MockPrometheusService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPrometheusService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPrometheusService {
	mock := &MockPrometheusService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
