export enum REALTIME_CONST {
  CONNECTED = "CONNECTED",
  PONG = "PONG",
  PING = "PING",
  TREE = "TREE",
  EVENT = "EVENT",
  LOG = "LOG",
  START_WATCH_LOGS = "START_WATCH_LOGS",
  ADD_RESOURCE = "ADD_RESOURCE",
  UPDATE_RESOURCE = "UPDATE_RESOURCE",
  DELETE_RESOURCE = "DELETE_RESOURCE",

}
