export enum REALTIME_CONST {
  CONNECTED = "CONNECTED",
  PONG = "PONG",
  PING = "PING",
  EVENT = "EVENT",
  LOG = "LOG",
  START_WATCH_LOGS = "START_WATCH_LOGS",
  RESOURCE_SYNC = "RESOURCE_SYNC",
  RESOURCE_PATCH = "RESOURCE_PATCH",
}
