name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "yarn"
          cache-dependency-path: web/yarn.lock

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.26"

      - name: Extract version from tag
        id: versioning
        run: |
          version="${GITHUB_REF_NAME}"
          echo "version=$version" >> $GITHUB_ENV
          echo "Version: $version"

      - name: Build all
        run: |
          make build VER=${{ env.version }}

      - name: Test all
        run: |
          make test

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t ghcr.io/timp4w/phi:${{ env.version }} -f docker/Dockerfile .
          docker push ghcr.io/timp4w/phi:${{ env.version }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.version }}
          name: "Release ${{ env.version }}"
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
